/**
 * City -> ISO-3166 alpha-2 country code for the whole addable-city catalog, plus
 * code -> English country name. Drives the "Before you fly" surface (public
 * holidays via Nager.Date, currency/FX via REST Countries + Frankfurter, entry +
 * visa reminders) and the concierge grounding facts. The city->code map is
 * derived straight from {@link GLOBAL_CITIES}, so every catalog city resolves;
 * cities added via free-text search resolve to `undefined` and degrade gracefully
 * (those rows simply hide). Country names cover every code the catalog uses.
 */
import { GLOBAL_CITIES } from './globalCities';

/** id -> ISO alpha-2, for every city in the global catalog. */
export const CITY_COUNTRY_CODES: Record<string, string> = Object.fromEntries(
  GLOBAL_CITIES.map((c) => [c.id, c.countryCode]),
);

/**
 * ISO alpha-2 -> English country name, so notes read "…for Thailand" not "…for
 * TH". Covers every code present in the catalog. Names for the codes that are
 * also selectable home countries match `homeCountry.ts` exactly, so the entry
 * reminder's same-country check (home name === dest name) resolves cleanly.
 */
export const COUNTRY_NAMES: Record<string, string> = {
  AE: 'United Arab Emirates',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BJ: 'Benin',
  BO: 'Bolivia',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'DR Congo',
  CH: 'Switzerland',
  CI: "Côte d'Ivoire",
  CL: 'Chile',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GH: 'Ghana',
  GM: 'Gambia',
  GR: 'Greece',
  GT: 'Guatemala',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LK: 'Sri Lanka',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MA: 'Morocco',
  ME: 'Montenegro',
  MG: 'Madagascar',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PL: 'Poland',
  PR: 'Puerto Rico',
  PT: 'Portugal',
  PY: 'Paraguay',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SN: 'Senegal',
  SR: 'Suriname',
  SV: 'El Salvador',
  TG: 'Togo',
  TH: 'Thailand',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Türkiye',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WS: 'Samoa',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export function countryCodeFor(stopId: string): string | undefined {
  return CITY_COUNTRY_CODES[stopId];
}

export function countryNameFor(code?: string): string | undefined {
  if (!code) return undefined;
  return COUNTRY_NAMES[code.toUpperCase()];
}
